#!/usr/bin/env bash
###############################################################################
# Cron Job Execution Script
# 由 cron 調用的實際執行腳本
###############################################################################

set -e

# 日期和時間
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
TODAY=$(date +"%Y-%m-%d")

# 路徑設定
PROJECT_ROOT="/Users/mhhung/Development/MH/market-intelligence-system"
LOG_FILE="/tmp/market-intelligence-system.log"

# 環境變數 (macOS cron 環境變數受限,需要明確設定 PATH)
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:$HOME/.local/bin:$HOME/.nvm/versions/node/*/bin"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# 寫入日誌的函數
log() {
    echo "[${TIMESTAMP}] $1" | tee -a "${LOG_FILE}"
}

# 開始執行
log "============================================================"
log "📊 Market Intelligence System - Daily Analysis Started"
log "============================================================"

# 切換到專案目錄
cd "${PROJECT_ROOT}" || {
    log "❌ 錯誤: 無法切換到專案目錄 ${PROJECT_ROOT}"
    exit 1
}

log "📂 工作目錄: $(pwd)"

# 執行完整的每日分析工作流程
log "🚀 開始執行 make daily (fetch-all + analyze-daily)..."

if make daily >> "${LOG_FILE}" 2>&1; then
    log "✅ 每日分析完成!"

    # 顯示生成的報告路徑
    MARKET_REPORT="${PROJECT_ROOT}/reports/markdown/market-analysis-${TODAY}.md"
    HOLDINGS_REPORT="${PROJECT_ROOT}/reports/markdown/holdings-analysis-${TODAY}.md"

    if [[ -f "${MARKET_REPORT}" ]]; then
        log "📈 市場分析報告: ${MARKET_REPORT}"
    fi

    if [[ -f "${HOLDINGS_REPORT}" ]]; then
        log "💼 持倉分析報告: ${HOLDINGS_REPORT}"
    fi

    log "✅ 所有任務執行成功!"
else
    log "❌ 執行失敗,請檢查日誌: ${LOG_FILE}"
    exit 1
fi

# Git 提交報告
log "📝 開始 Git 提交..."

# 檢查是否有變更
if git -C "${PROJECT_ROOT}" status --porcelain | grep -q "reports/markdown"; then
    log "   發現 markdown 報告變更,準備提交..."

    # 添加報告檔案
    git -C "${PROJECT_ROOT}" add reports/markdown/*.md >> "${LOG_FILE}" 2>&1 || true

    # 提交變更
    if git -C "${PROJECT_ROOT}" commit -m "feat(daily): Update analysis reports for ${TODAY}

📊 自動生成的每日市場分析報告

- 市場分析報告: market-analysis-${TODAY}.md
- 持倉分析報告: holdings-analysis-${TODAY}.md

🤖 Generated by Market Intelligence System (Cron Job)" >> "${LOG_FILE}" 2>&1; then
        log "✅ Git 提交成功!"

        # 推送到 remote (可選,如果你希望自動推送)
        # 注意: 需要先設定 SSH key 或 credential helper
        if git -C "${PROJECT_ROOT}" push origin main >> "${LOG_FILE}" 2>&1; then
            log "✅ Git 推送成功!"
        else
            log "⚠️  Git 推送失敗 (可能需要手動推送或設定認證)"
        fi
    else
        log "⚠️  Git 提交失敗或無內容變更"
    fi
else
    log "   ℹ️  沒有 markdown 報告變更,跳過 Git 提交"
fi

log "============================================================"
log "📊 Market Intelligence System - Daily Analysis Completed"
log "============================================================"
