#!/usr/bin/env bash
###############################################################################
# Market Intelligence System - Cron Job Setup for macOS
#
# 設定定時任務:
# - 早上 08:00 執行 (美國收盤後的新聞)
# - 晚上 20:00 執行 (亞洲收盤後的新聞)
#
# 使用方式:
#   chmod +x setup_cron.sh
#   ./setup_cron.sh
###############################################################################

set -e

# 顏色定義
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# 獲取專案根目錄的絕對路徑
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="/tmp/market-intelligence-system.log"

echo -e "${BLUE}============================================================${NC}"
echo -e "${BLUE}📅 Market Intelligence System - Cron Job 設定${NC}"
echo -e "${BLUE}============================================================${NC}"
echo ""

echo -e "${GREEN}專案路徑: ${PROJECT_ROOT}${NC}"
echo -e "${GREEN}日誌檔案: ${LOG_FILE}${NC}"
echo ""

# 檢查依賴
echo -e "${BLUE}🔍 檢查依賴...${NC}"

# 檢查 Python
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}❌ 錯誤: 未安裝 Python 3${NC}"
    exit 1
fi
echo -e "${GREEN}   ✅ Python 3: $(python3 --version)${NC}"

# 檢查 make
if ! command -v make &> /dev/null; then
    echo -e "${RED}❌ 錯誤: 未安裝 make${NC}"
    exit 1
fi
echo -e "${GREEN}   ✅ Make: $(make --version | head -1)${NC}"

# 檢查 Claude CLI
if ! command -v claude &> /dev/null; then
    echo -e "${YELLOW}⚠️  警告: 未安裝 Claude CLI${NC}"
    echo -e "${YELLOW}   請執行: npm install -g @anthropic-ai/claude-cli${NC}"
    echo -e "${YELLOW}   然後執行: claude login${NC}"
else
    echo -e "${GREEN}   ✅ Claude CLI 已安裝${NC}"
fi

echo ""

# 創建 cron 任務腳本
echo -e "${BLUE}📝 創建 cron 執行腳本...${NC}"

CRON_SCRIPT="${PROJECT_ROOT}/run_daily_cron.sh"

cat > "${CRON_SCRIPT}" <<'CRON_EOF'
#!/usr/bin/env bash
###############################################################################
# Cron Job Execution Script
# 由 cron 調用的實際執行腳本
###############################################################################

set -e

# 日期和時間
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
TODAY=$(date +"%Y-%m-%d")

# 路徑設定
PROJECT_ROOT="__PROJECT_ROOT__"
LOG_FILE="__LOG_FILE__"

# 環境變數 (macOS cron 環境變數受限,需要明確設定 PATH)
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:$HOME/.local/bin:$HOME/.nvm/versions/node/*/bin"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# 寫入日誌的函數
log() {
    echo "[${TIMESTAMP}] $1" | tee -a "${LOG_FILE}"
}

# 開始執行
log "============================================================"
log "📊 Market Intelligence System - Daily Analysis Started"
log "============================================================"

# 切換到專案目錄
cd "${PROJECT_ROOT}" || {
    log "❌ 錯誤: 無法切換到專案目錄 ${PROJECT_ROOT}"
    exit 1
}

log "📂 工作目錄: $(pwd)"

# 執行完整的每日分析工作流程
log "🚀 開始執行 make daily (fetch-all + analyze-daily)..."

if make daily >> "${LOG_FILE}" 2>&1; then
    log "✅ 每日分析完成!"

    # 顯示生成的報告路徑
    MARKET_REPORT="${PROJECT_ROOT}/reports/markdown/market-analysis-${TODAY}.md"
    HOLDINGS_REPORT="${PROJECT_ROOT}/reports/markdown/holdings-analysis-${TODAY}.md"

    if [[ -f "${MARKET_REPORT}" ]]; then
        log "📈 市場分析報告: ${MARKET_REPORT}"
    fi

    if [[ -f "${HOLDINGS_REPORT}" ]]; then
        log "💼 持倉分析報告: ${HOLDINGS_REPORT}"
    fi

    log "✅ 所有任務執行成功!"
else
    log "❌ 執行失敗,請檢查日誌: ${LOG_FILE}"
    exit 1
fi

# Git 提交報告
log "📝 開始 Git 提交..."

# 檢查是否有變更
if git -C "${PROJECT_ROOT}" status --porcelain | grep -q "reports/markdown"; then
    log "   發現 markdown 報告變更,準備提交..."

    # 添加報告檔案
    git -C "${PROJECT_ROOT}" add reports/markdown/*.md >> "${LOG_FILE}" 2>&1 || true

    # 提交變更
    if git -C "${PROJECT_ROOT}" commit -m "feat(daily): Update analysis reports for ${TODAY}

📊 自動生成的每日市場分析報告

- 市場分析報告: market-analysis-${TODAY}.md
- 持倉分析報告: holdings-analysis-${TODAY}.md

🤖 Generated by Market Intelligence System (Cron Job)" >> "${LOG_FILE}" 2>&1; then
        log "✅ Git 提交成功!"

        # 推送到 remote (可選,如果你希望自動推送)
        # 注意: 需要先設定 SSH key 或 credential helper
        if git -C "${PROJECT_ROOT}" push origin main >> "${LOG_FILE}" 2>&1; then
            log "✅ Git 推送成功!"
        else
            log "⚠️  Git 推送失敗 (可能需要手動推送或設定認證)"
        fi
    else
        log "⚠️  Git 提交失敗或無內容變更"
    fi
else
    log "   ℹ️  沒有 markdown 報告變更,跳過 Git 提交"
fi

log "============================================================"
log "📊 Market Intelligence System - Daily Analysis Completed"
log "============================================================"
CRON_EOF

# 替換腳本中的變數
sed -i '' "s|__PROJECT_ROOT__|${PROJECT_ROOT}|g" "${CRON_SCRIPT}"
sed -i '' "s|__LOG_FILE__|${LOG_FILE}|g" "${CRON_SCRIPT}"

# 設定執行權限
chmod +x "${CRON_SCRIPT}"

echo -e "${GREEN}   ✅ Cron 執行腳本已創建: ${CRON_SCRIPT}${NC}"
echo ""

# 備份現有的 crontab
echo -e "${BLUE}📋 備份現有 crontab...${NC}"
BACKUP_FILE="${PROJECT_ROOT}/crontab.backup.$(date +%Y%m%d_%H%M%S)"
crontab -l > "${BACKUP_FILE}" 2>/dev/null || echo "# No existing crontab" > "${BACKUP_FILE}"
echo -e "${GREEN}   ✅ 備份已保存: ${BACKUP_FILE}${NC}"
echo ""

# 生成新的 crontab 內容
echo -e "${BLUE}📝 生成新的 crontab 設定...${NC}"
TEMP_CRONTAB="/tmp/mis_crontab_$$"

# 複製現有 crontab (排除舊的 MIS 任務)
crontab -l 2>/dev/null | grep -v "market-intelligence-system" > "${TEMP_CRONTAB}" || true

# 添加新的 cron 任務
cat >> "${TEMP_CRONTAB}" <<EOF

# ============================================================
# Market Intelligence System - 自動化市場分析
# ============================================================
# 早上 08:00 執行 (美國收盤後的新聞)
0 8 * * * ${CRON_SCRIPT}

# 晚上 20:00 執行 (亞洲收盤後的新聞)
0 20 * * * ${CRON_SCRIPT}
# ============================================================
EOF

echo ""
echo -e "${YELLOW}即將安裝以下 cron 任務:${NC}"
echo -e "${YELLOW}------------------------------------------------------------${NC}"
cat "${TEMP_CRONTAB}"
echo -e "${YELLOW}------------------------------------------------------------${NC}"
echo ""

# 詢問確認
read -p "是否安裝這些 cron 任務? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    crontab "${TEMP_CRONTAB}"
    echo -e "${GREEN}✅ Cron 任務已安裝!${NC}"
    echo ""

    echo -e "${BLUE}📋 當前 crontab 設定:${NC}"
    echo -e "${BLUE}------------------------------------------------------------${NC}"
    crontab -l
    echo -e "${BLUE}------------------------------------------------------------${NC}"
    echo ""

    echo -e "${GREEN}🎉 設定完成!${NC}"
    echo ""
    echo -e "${BLUE}執行時間:${NC}"
    echo -e "  • 每天早上 08:00 (美國收盤後)"
    echo -e "  • 每天晚上 20:00 (亞洲收盤後)"
    echo ""
    echo -e "${BLUE}日誌位置:${NC}"
    echo -e "  ${LOG_FILE}"
    echo ""
    echo -e "${BLUE}查看日誌:${NC}"
    echo -e "  tail -f ${LOG_FILE}"
    echo ""
    echo -e "${BLUE}手動測試執行:${NC}"
    echo -e "  ${CRON_SCRIPT}"
    echo ""
    echo -e "${BLUE}移除 cron 任務:${NC}"
    echo -e "  crontab -e  # 然後手動刪除 Market Intelligence System 相關行"
    echo ""
    echo -e "${BLUE}還原備份:${NC}"
    echo -e "  crontab ${BACKUP_FILE}"
    echo ""
else
    echo -e "${YELLOW}❌ 已取消安裝${NC}"
    rm -f "${TEMP_CRONTAB}"
    exit 0
fi

# 清理臨時檔案
rm -f "${TEMP_CRONTAB}"

echo -e "${GREEN}✅ 所有設定完成!${NC}"
